# Generated by Django 4.2.11 on 2024-06-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0006_medicalrecord_doctor_alter_appointment_patient_and_more'),
        ('doctor_app', '0006_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patient_appointments', to='patient_app.patient'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patient_medical_records', to='patient_app.patient'),
        ),
    ]
