# Generated by Django 4.2.11 on 2024-06-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0008_facilitymanagement'),
        ('doctor_app', '0007_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patient_app.patient'),
        ),
    ]
