# Generated by Django 4.2.11 on 2024-06-22 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_alter_doctorprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_app', '0002_patient_delete_patientprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_and_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='doctor_app.doctorprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default=1234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
