# Generated by Django 4.2.11 on 2024-06-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_rename_date_and_time_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
