# Generated by Django 4.2.11 on 2024-06-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0006_alter_appointment_doctor'),
        ('patient_app', '0004_remove_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_appointments', to='doctor_app.doctorprofile'),
        ),
    ]
