# Generated by Django 4.2.11 on 2024-06-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0006_alter_appointment_doctor'),
        ('patient_app', '0005_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='doctors_record', to='doctor_app.doctorprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient_app.patient'),
        ),
        migrations.AlterField(
            model_name='billingstatement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_billing', to='patient_app.patient'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_records', to='patient_app.patient'),
        ),
    ]
