# Generated by Django 4.2.11 on 2024-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0007_rename_date_appointment_date_and_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=15)),
            ],
        ),
    ]
