# Generated by Django 4.2.11 on 2024-06-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0008_facilitymanagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingstatement',
            name='patient',
        ),
        migrations.AddField(
            model_name='billingstatement',
            name='appointment',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='billing_statements', to='patient_app.appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingstatement',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
