# Generated by Django 4.2.11 on 2024-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='user',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='name',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
