# Generated by Django 4.2.11 on 2024-06-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_alter_appointment_doctor'),
        ('doctor_app', '0006_alter_appointment_doctor'),
        ('admin_app', '0002_remove_usermanagement_user_usermanagement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='facility',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, related_name='admin_appointments', to='doctor_app.doctorprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_patient_appointments', to='patient_app.patient'),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
