# Generated by Django 4.2.11 on 2024-06-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_adminprofile_alter_doctorprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='permission',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
