# Generated by Django 4.2.11 on 2024-06-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_remove_patient_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilitymanagement',
            old_name='resources',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='facilitymanagement',
            old_name='location',
            new_name='name',
        ),
    ]
