# Generated by Django 4.2.11 on 2024-06-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_rename_resources_facilitymanagement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitymanagement',
            name='department',
            field=models.CharField(max_length=15),
        ),
    ]
